name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      run: |
        gem install bundler
        bundle install
        bundle exec rake
    - name: Run the actual server
      run: |
        bundle exec ruby bin/right_speed -c snippets/test.ru &
        sleep 5
        output=$(curl -s http://127.0.0.1:8228)
        kill %1
        test "$output" = "Yaay"
    - name: Run rackup
      run: |
        echo "to be implemented later"
